all:
  children:
    application:
    benchmarker:
application:
  hosts:
    isucon13-1:
      ansible_host: 10.0.1.246
      ansible_user: ubuntu
    isucon13-2:
      ansible_host: 10.0.1.79
      ansible_user: ubuntu
    isucon13-3:
      ansible_host: 10.0.1.60
      ansible_user: ubuntu
    isucon13-bench:
      ansible_host: 10.0.1.218
      ansible_user: ubuntu
benchmarker:
  hosts:
    isucon13-bench:
      ansible_host: 10.0.1.218
      ansible_user: ubuntu

